# Generated by Django 2.0.5 on 2020-05-10 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirPlane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bort_number', models.CharField(max_length=64, unique=True)),
                ('on_service', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AirTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=16)),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AviaCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('start_date_TS', models.DateField()),
                ('end_date_TS', models.DateField()),
                ('penalty_coef', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_amount', models.PositiveSmallIntegerField()),
                ('duration', models.PositiveIntegerField()),
                ('contract_amount', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='s7technics.AviaCompany')),
            ],
        ),
        migrations.CreateModel(
            name='Hangar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DME', 'Домодедово'), ('SVO', 'Шереметьево'), ('VKO', 'Внуково')], default='DME', max_length=3)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('is_filled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('C', 'C-Check'), ('D', 'D-Check'), ('R', 'Redelivery'), ('P', 'Painting')], max_length=1)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('airplane_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='s7technics.AirTypes')),
                ('hangar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='s7technics.Hangar')),
            ],
        ),
        migrations.AddField(
            model_name='companyrequirement',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='s7technics.TechnicalService'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='plane_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='s7technics.AirTypes'),
        ),
        migrations.AlterUniqueTogether(
            name='technicalservice',
            unique_together={('type', 'airplane_type')},
        ),
    ]
