# Generated by Django 2.0.5 on 2020-05-10 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s7technics', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='technicalservice',
            unique_together={('type', 'airplane_type', 'hangar')},
        ),
    ]
